# Sudoku Project
by Finn Potason (s2.wang@vu.nl)

This is a quick tutorial for MSc Logic students and those who struggle to kick off the project.

First of all you need the Pycosat solver [1].
In your terminal [2], type: pip install pycosat

[1] See more details at: https://pypi.python.org/pypi/pycosat
[2] Press ctrl + alt + t.

Next we test if the solver is working: 

In [131]:
import pycosat
cnf = [[1, 5,4], [-1,5,3,4], [-3, -4]]
pycosat.solve(cnf)
from math import sqrt

Next, you can print all the possible assignments to this CNF. 

In [2]:
print ('There are in total ', len(list(pycosat.itersolve(cnf))), ' possible assignments:')
for sol in pycosat.itersolve(cnf):
    print(sol)


There are in total  18  possible assignments:
[1, -2, -3, -4, 5]
[1, -2, -3, 4, -5]
[1, -2, -3, 4, 5]
[1, -2, 3, -4, -5]
[1, -2, 3, -4, 5]
[1, 2, 3, -4, -5]
[1, 2, 3, -4, 5]
[1, 2, -3, -4, 5]
[1, 2, -3, 4, -5]
[1, 2, -3, 4, 5]
[-1, 2, -3, 4, -5]
[-1, 2, -3, 4, 5]
[-1, 2, -3, -4, 5]
[-1, 2, 3, -4, 5]
[-1, -2, 3, -4, 5]
[-1, -2, -3, -4, 5]
[-1, -2, -3, 4, -5]
[-1, -2, -3, 4, 5]


## Encode Sudoku
Take a random sudoku and think what the propositional variables are.
PS: You will need the library numpy. If you don't have it, install it (and reboot if needed).

In [3]:
import numpy as np
s_test = np.array([[8,0,6,5,0,0,0,0,0],
                    [0,0,4,0,0,0,0,0,8],
                    [0,0,0,0,0,0,6,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [3,7,0,4,5,0,0,0,0],
                    [5,0,1,0,9,8,0,0,7],
                    [0,0,0,0,0,7,0,2,0],
                    [2,5,7,1,6,0,0,0,9],
                    [0,8,0,0,3,0,0,4,0]])
print(s_test)

[[8 0 6 5 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 8]
 [0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 0 0]
 [3 7 0 4 5 0 0 0 0]
 [5 0 1 0 9 8 0 0 7]
 [0 0 0 0 0 7 0 2 0]
 [2 5 7 1 6 0 0 0 9]
 [0 8 0 0 3 0 0 4 0]]


In [152]:
n = 9

names = np.zeros([n,n,n], dtype = np.int)
ids = list()
ids.append((-1,-1,-1))
index = 1
for i in range(n):
    for j in range(n):
#         print('introduce a 9 propositional variables to each cell:')
        for k in range(n):
            name = i * n**2 + j * n + k+1
            names[i][j][k] = name
            ids.append((i+1,j+1,k+1))
#             print('if the cell at row: ', i+1, ' column: ', j+1, 'is ', k+1, 'then it is named ', names[i][j][k])

In [153]:
def get_name(names, i, j, k):
    return names[i-1, j-1, k-1]

print(ids[7])
# get_name(names, 9,9,9)

(1, 1, 7)


In [154]:
# print ('When the cell at row 3 column 4 is 6')
# print('the variable' , names[2][3][5], ' is true')
# print('please be careful about the indexing!!!')

In [155]:
encode_cnf = []
print('start populate this cnf:', encode_cnf)

start populate this cnf: []


Next, we define two functions to obtain the function exactly one. 

In [156]:
def encode_at_most_one(names):
    encode = []
    for i in range(n):
        for j in range(n):
            for k in range(n-1):
                for l in range(k+1, n):
                    arr = [-names[i,j,k], -names[i,j,l]]
#             names_i = [list(n) for n in -names[i]]
#             names_j = [list(n) for n in -names[j]]
#             arr = names_i + names_j
                    encode.append(arr)
    return encode
      
# test_names = [1,2,3]
# enc = encode_at_most_one(names)
# print('at most one is encoded as: ', enc1)
# encode_cnf.extend(enc1)

def encode_at_least_one(names):
    encode = []
    for i in range(n):
        for j in range(n):
            arr = [names[i][j][k] for k in range(n)]
            encode.append(arr)
    return encode

# enc2 = encode_at_least_one(names)
# print('at least one is encoded as:', enc)
# encode_cnf.extend(enc)

# print('put them together, you get: ', flat_list)

# print ('as you can see, there is exactly one true:')
# print("a", type(encode_cnf))
# pycosat.solve(flat_list)



In [157]:


pycosat.itersolve(exactly_one(names))

TypeError: integer expected

In [158]:
for i in [721, 722, 723, 724, 725, 726, 727, 728, 729]:
    print(ids[i])

(9, 9, 1)
(9, 9, 2)
(9, 9, 3)
(9, 9, 4)
(9, 9, 5)
(9, 9, 6)
(9, 9, 7)
(9, 9, 8)
(9, 9, 9)


## 1) For each cell, exactly one variable is true.

In [159]:
def exactly_one(names):
    enc1 = encode_at_most_one(names)
    enc2 = encode_at_least_one(names)
    return enc1 + enc2

print(exactly_one(names))

[[-1, -2], [-1, -3], [-1, -4], [-1, -5], [-1, -6], [-1, -7], [-1, -8], [-1, -9], [-2, -3], [-2, -4], [-2, -5], [-2, -6], [-2, -7], [-2, -8], [-2, -9], [-3, -4], [-3, -5], [-3, -6], [-3, -7], [-3, -8], [-3, -9], [-4, -5], [-4, -6], [-4, -7], [-4, -8], [-4, -9], [-5, -6], [-5, -7], [-5, -8], [-5, -9], [-6, -7], [-6, -8], [-6, -9], [-7, -8], [-7, -9], [-8, -9], [-10, -11], [-10, -12], [-10, -13], [-10, -14], [-10, -15], [-10, -16], [-10, -17], [-10, -18], [-11, -12], [-11, -13], [-11, -14], [-11, -15], [-11, -16], [-11, -17], [-11, -18], [-12, -13], [-12, -14], [-12, -15], [-12, -16], [-12, -17], [-12, -18], [-13, -14], [-13, -15], [-13, -16], [-13, -17], [-13, -18], [-14, -15], [-14, -16], [-14, -17], [-14, -18], [-15, -16], [-15, -17], [-15, -18], [-16, -17], [-16, -18], [-17, -18], [-19, -20], [-19, -21], [-19, -22], [-19, -23], [-19, -24], [-19, -25], [-19, -26], [-19, -27], [-20, -21], [-20, -22], [-20, -23], [-20, -24], [-20, -25], [-20, -26], [-20, -27], [-21, -22], [-21, -23], [-2

## 2) For each row, for each number, exactly one propositional variable is true.

In [160]:
def atleast_row(names):
    encode = []
    for j in range(n):
        for k in range(n):
            arr = [names[i][j][k] for i in range(n)]
            encode.append(arr)
    return encode

def atmost_row(names):
    encode = []
    for k in range(n):
        for l in range(n):
            for i in range(n-1):
                for j in range(i+1, n):
                    arr = [-names[i,k,l], -names[j,k,l]]
                    encode.append(arr)
    return encode

def exactly_one_row(names):
    enc1 = atmost_row(names)
    enc2 = atleast_row(names)
    return enc1 + enc2

print(exactly_one_row(names))

[[-1, -82], [-1, -163], [-1, -244], [-1, -325], [-1, -406], [-1, -487], [-1, -568], [-1, -649], [-82, -163], [-82, -244], [-82, -325], [-82, -406], [-82, -487], [-82, -568], [-82, -649], [-163, -244], [-163, -325], [-163, -406], [-163, -487], [-163, -568], [-163, -649], [-244, -325], [-244, -406], [-244, -487], [-244, -568], [-244, -649], [-325, -406], [-325, -487], [-325, -568], [-325, -649], [-406, -487], [-406, -568], [-406, -649], [-487, -568], [-487, -649], [-568, -649], [-2, -83], [-2, -164], [-2, -245], [-2, -326], [-2, -407], [-2, -488], [-2, -569], [-2, -650], [-83, -164], [-83, -245], [-83, -326], [-83, -407], [-83, -488], [-83, -569], [-83, -650], [-164, -245], [-164, -326], [-164, -407], [-164, -488], [-164, -569], [-164, -650], [-245, -326], [-245, -407], [-245, -488], [-245, -569], [-245, -650], [-326, -407], [-326, -488], [-326, -569], [-326, -650], [-407, -488], [-407, -569], [-407, -650], [-488, -569], [-488, -650], [-569, -650], [-3, -84], [-3, -165], [-3, -246], [-3,

## 3) For each column, for each number, exactly one varialbe is true.

In [ ]:
def atleast_column(names):
    encode = []
    for i in range(n):
        for k in range(n):
            arr = [names[i][j][k] for j in range(n)]
            encode.append(arr)
    return encode

def atmost_column(names):
    encode = []
    for i in range(n):
        for l in range(n):
            for j in range(n-1):
                for k in range(j+1, n):
                    arr = [-names[i,j,l], -names[i,k,l]]
                    encode.append(arr)
    return encode

def exactly_one_column(names):
    enc1 = atmost_column(names)
    enc2 = atleast_column(names)
    return enc1 + enc2

print(exactly_one_column(names))

## 4) For each block, for each number, exactly one variable is true.

In [ ]:
def atleast_region(names):
    encode = []
    for i in range(n):
        for k in range(n):
            arr = [names[i][j][k] for j in range(n)]
            encode.append(arr)
    return encode

def atmost_region(names):
    encode = []
    region_size = int(sqrt(n))

    for a in range(n):
        for b in range(region_size - 1):
            for c in range(region_size - 1):
                for d in range(region_size):
                    for e in range(region_size):
                        for f in range(e+1, region_size):
                            literal = -names[(region_size*b+e),(region_size*c+e), a]
                            literal2 = -names[(region_size*b+e),(region_size*c+f), a]
                            encode.append([literal, literal2])
                        for f in range(d+1, region_size):
                            for g in range(region_size):
                                literal = -names[(region_size*b+e),(region_size*c+e), a]
                                literal2 = -names[(region_size*b+f),(region_size*c+g), a]
                                encode.append([literal, literal2])
    return encode

def exactly_one_region(names):
    enc1 = atmost_region(names)
    enc2 = atleast_region(names)
    return enc1 + enc2


## 5) Now put them together and see if your solver returns an assignment

In [140]:
print(ids[82])

(2, 1, 1)


In [ ]:
# TODO

## 6) What does this assignment tell you? Can you decode it and print the solution (mind the indices)?